name: build web
on: push
jobs :
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
         # flutter-version: '2.16.1'
      - name: Build web
       # verification des dépendances et du format puis analyse et test
        run: |
          flutter pub get
          flutter format --set-exit-if-changed .
          flutter analyze
          flutter test
          flutter build web
